### ISSUE TITLE
Movie Info During Playback

### ISSUE THREAD

**Issue by kavuraki** [DiMartinoXBMC/plugin.video.torrenter#54]
When I'm using Torrenter Search context menu or regular search menu on the add-on there's no movie poster and no appropriate movie name during playback  If I click (i)nfo. But If I start the movie from content list there's a movie poster during playback but the name is again <moviename>.MKV etc....

**Comment by mancuniancol** [comment]
I am not sure if the issue is the same.  I am using Torrenter V2 to play torrents from my own add-on.  Despite of I am giving the infolabels, Torrenter  seems to ignore them.  If I use another torrent player the information is taken.

`        
link = 'plugin://plugin.video.torrenter/?action=playSTRM&url=' + uri_string + '&not_download_only=True'
info['FileName'] = filename
info['Path'] = filename
list_item = xbmcgui.ListItem(info["Title"])
list_item.setInfo('video', info)
list_item.setProperty("IsPlayable", "true")
xbmc.Player().play(link, list_item, False)`

The variable info is a dictionary with some infolabels like plot, label, title.  But, even just given the xbmcgui.ListItem("My Title") doesn't work.

There is something that I am missing or it is not implemented yet?

Thank you in advance for your time.

**Comment by DiMartinoXBMC** [comment]
well as far as I remember I've added only poster support, before playing Torrenter creates it'd own [xbmcgui.listitem in the "player"](https://github.com/DiMartinoXBMC/plugin.video.torrenter/blob/master/Inposloader.py#L450), so it does not use any of yours info. maybe it's just wrong coding and plugin can start. What plugins work as you intent, I can see and copy some code?

**Comment by mancuniancol** [comment]
YATP works perfectly. It gets title, plot,  etc. 

https://github.com/romanvm/kodi.yatp

That would be great if you can enable that in Torrenter. Please, let me know if you need any help.
